### ISSUE TITLE
null

### ISSUE THREAD

**Issue by rllm-project** [THUDM/GraphMAE2#4]

**Comment by THINK2TRY** [comment]
Hi @beckvision , sorry for the late response. We use seed 0-19 just for 20 random experiments to obtain the average performance following the setting of previous works,  rather than for other special purposes. The performance in Cora / Citeseer / PubMed are more unstable among different seeds since the training and test set are too small.  We run the experiments on 2080 Ti and A100 (40G) and could get almost the same average performance for more seeds. Could you provide more details about your enviroment?

**Comment by beckvision** [comment]
I together with my friends have test on several servers, but cannot get your reported performance with random seeds.

Let's wired, and let us to see others whether they have the same problem.

**Comment by beckvision** [comment]
I together with my friends have test on several servers, but cannot get your reported performance with random seeds.

Let's wired, and let us to see others whether they have the same problem.
