### ISSUE TITLE
Graph classification experiments

### ISSUE THREAD

**Issue by cxw-droid** [THUDM/GraphMAE2#5]
Hello, the GraphMAE2 paper does not have graph classification downstream task experiments. Does it mean GraphMAE2 is not applicable to graph classification or is there any other reason? Thanks.

**Comment by THINK2TRY** [comment]
Hi @cxw-droid, thanks for your attention! GraphMAE2 can also be applied to other tasks like graph classification. Since GraphMAE2 mainly aims to tackle the problems of real-world noise and scalability, we conduct experiments on web-scale datasets, which are close to real applications. Actually, GraphMAE2 can be used to graph classification with the same pipeline as GraphMAE.

**Comment by cxw-droid** [comment]
Hi @THINK2TRY , thank you for the reply. Did you test GraphMAE2 on graph classification or how do you expect its performance?

**Comment by THINK2TRY** [comment]
@cxw-droid We didn't run experiments on graph classification tasks so far. It can be expected that GraphMAE2 may have similar performance to GraphMAE and the improvement would not be as significant as that in node classification. As observed from the difference of results in OGB and Cora/Citeseer, the input features for graph classification benchmarks are also usually 0/1 vectors or degrees, which may benefit relatively less from the improvement.
